AllCops:
  Exclude:
    - test/**/*
    - vendor/**/*
    - cookbooks/**/*
    - Guardfile
AlignParameters:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Max: 30
RescueModifier:
  Enabled: false
FileName:
  Enabled: false
